<?php 
$user_error = "";
$debug_text = "it works ! and debug is on";

// Controler
include_once('littlesFunctions.php');
include_once('model/connectDb.php');
include_once('model/deleteUser.php');
include_once('model/deleteIncidents.php');
include_once('model/selectTable.php');

// Debug variable
$debug = false;
// User id generated by mysql database
$user_id = false;

  // Delete GET id 
  if (isset($_GET['id']) 
    && $_GET['id'] != '' 
    &&  is_numeric($_GET['id'])
    && $_GET['delete'] == '1'
    && isset($_GET['type'])
    && $_GET['type'] != '' ) {
      if ($_GET['type'] == '1') {
        // check if User is link to incidents
        deleteUser($_GET['id'], $user_error);
      } elseif ($_GET['type'] == '2') {
        // delete related image 
        deleteIncidents($_GET['id']);
      }
  }

  // Get users info 
  $nbDisplay = 50;
  $users = selectTable('users', $nbDisplay);
  $incidents = selectTable('incident', $nbDisplay);

  // TODO if more than 50 add arrows
  if (!isset($_GET['no_anim'])) {
    $no_anim = false;
  } else {
    $no_anim = $_GET['no_anim'];
  }

?>

<?php // View  ?>
<?php include_once('myHeader.php'); ?>
<?php include_once('nav.php'); ?>
 
<?php myHeader_fr("Incidents"); ?>
  <body>
    <?php myNav("admin"); ?>
      <?php if ($user_error !== "") { ?>
        <div class=" row wow fadeInDown">
          <div class="col-md-12">
          <div class="col-md-12 alert  alert-warning">
            <a href="form.php?no_anim=true" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <h4>
              <?php echo $user_error; ?> 
            </h4>
          </div>
          </div>
        </div>
      <?php } ?>
    <?php if ($debug) { ?>
      <div class=" row wow fadeInDown">
        <div class="col-md-12">
          <div class="col-md-12 alert alert-success">
            <a href="form.php?no_anim=true" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <h4>
              <?php echo $debug_text; ?>
            </h4>
          </div>
        </div>
      </div>
    <?php } ?>
    
  	<!-- <button type="button" class="btn btn-default">Set Data Base</button>
  	<a href="model/create_ddb.php" class="btn btn-default" role="button">Set Data Base</a> -->

<div class="row <?php echo ($no_anim ? '' : 'wow') ?> fadeInRight">
  <div class="form-header " data-wow-delay="0.1s">
    <h1> Tables des utilisateurs.</h1>
    <h4> Voici toutes les utilisateurs qui ont rapporté des incidents.</h4>
    <header>Seulement les <?php echo $nbDisplay; ?> premiers sont representés.</header>
  </div>
  <table class="table table-hover">
    <thead> 
      <tr>
        <th>#</th>
        <th>Prénom</th>
        <th>Nom de famille</th>
        <th>E-mail</th>
        <th>Téléphone</th>
        <th>Supprimer</th>
      </tr>
    </thead> 
    <tbody>
      <?php foreach ($users as &$row) { ?>
      <tr>
        <th scope="row"><?php echo $row['id']?></th>
        <td><?php echo $row['firstname']?></td>
        <td><?php echo $row['lastname']?></td>
        <td><?php echo $row['email']?></td>
        <td><?php echo $row['tel']?></td>
        <td><a href="?<?php echo 'no_anim=true&delete=1&type=1&id='.$row['id']; ?>" role="button" class="btn btn-danger">x</a></td>
      </tr>
      <?php } ?>
    </tbody>
    <tr>
        <th><a href="form.php" role="button" class="btn btn-success">+</a></th>
      </tr>
  </table>
 </div>

 <div class="row <?php echo ($no_anim ? '' : 'wow') ?> fadeInLeft">
  <div class="form-header " data-wow-delay="0.1s">
    <h1> Tables des incidents.</h1>
    <h4> Voici toutes les incidents qui ont rapportés.</h4>
    <header>Terry Pratchett vous aimes ! </header>
  </div>
  <table class="table table-hover">
    <thead> 
      <tr>
        <th>#</th>
        <th>ID du rapporteur</th>
        <th>Description</th>
        <th>Severité</th>
        <th>Contact de préfèrence</th>
        <th>Image</th>
        <th>Supprimer</th>
      </tr>
    </thead> 
    <tbody>
      <?php foreach ($incidents as &$row) { ?>
      <tr>
        <th scope="row"><?php echo $row['id_incident']?></th>
        <td><?php echo $row['fk_pers']?></td>
        <td><?php echo $row['description']?></td>
        <td><?php echo $row['severite']?></td>
        <td><?php echo $row['pref']?></td>
        <td> <img src="<?php echo $row['srcImage']?>" class="img-responsive" alt="<?php echo $row['description']?>" height="70" width="70"> </td>
        <td><a href="?<?php echo 'no_anim=true&delete=1&type=2&id='.$row['id_incident']; ?>" role="button" class="btn btn-danger">x</a></td>
      </tr>
      <?php } ?>
    </tbody>
    <tr>
        <th><a href="form.php" role="button" class="btn btn-success">+</a></th>
      </tr>
  </table>
 </div>

<?php include_once('footer.php'); ?>


  </body>
   <script src="js/wow.min.js"></script>
              <script>
              new WOW().init();
              </script>
</html>